experiment:
  # It contains all the about the grids and the group of runs:
  name: LabelAnything # name of the logger platform experiment
  group: FirstTry # name of group of experiments for the logger platform
  continue_with_errors: False # continue with other runs even if a run fails
  start_from_grid: 0 # skip grids in the grid search
  start_from_run: 0 # skip runs from the selected grid

parameters:
  # Contains the parameters to build the grid.
  # Each value should be a dict or a list
  tags: [[mytag1, mytag2]] # list of tags to attach to the run in logger platform

  train_params:
    loss:
    seed: [42] # random seed to set
    # substitution_threshold: [0.1] # threshold 
    num_points: [1] # number of points for class after the substitution
    max_epochs: [2]
    compile: [False]
    logger:
      log_frequency: [20]
    initial_lr: [0.0001, 0.00005]
    optimizer: [AdamW]

  model:
    name: [lam_no_vit] # path to model class or model name contained in EzDL or super-gradients
    checkpoint: [checkpoints/sam_vit_b_01ec64.pth] # model parameters
    use_sam_checkpoint: [True]

  dataset: # parameters depending on the class you defined for the dataset
    datasets:
      lvis:
        instances_path: [data/raw/cocolvis/lvis_v1_train.json]
        emb_dir: [data/raw/embeddings]
      coco:
        instances_path: [data/raw/cocolvis/instances_train2017.json]
        emb_dir: [data/raw/embeddings]
      val_lvis:
        instances_path: [data/raw/cocolvis/lvis_v1_val.json]
        seed: [0]
        do_subsample: [False]
        add_box_noise: [False]
        emb_dir: [data/raw/embeddings]
      val_coco:
        instances_path: [data/raw/cocolvis/instances_val2017.json]
        seed: [0]
        do_subsample: [False]
        add_box_noise: [False]
        emb_dir: [data/raw/embeddings]
    common:
      max_num_examples: [2]
      load_embeddings: [True]
  dataloader:
    batch_size: [2]
    num_workers: [0]

other_grids: